---
title: "data"
author: "Jasmine Toh"
date: "11/4/2020"
output: html_document
---


Setup:
```{r setup, include<-FALSE}
knitr::opts_chunk$set(echo <- TRUE)
packages = c('tidyverse','leaflet', 'knitr','stringr','httr','geojsonio', 'sp', 'dplyr', 'SpatialAcc', 'rgeos', 'spdplyr', 'KernSmooth', 'raster',"reshape2", "sf") 
for (p in packages){
  if(!require(p, character.only = T)){ 
    install.packages(p)
  }
  library(p,character.only = T) 
}

memory.limit(size=56000)

# Data Paths
dp_prefix_a = "../data/aspatial/" 
dp_prefix_g = "../data/geospatial" 
dp_prefix_j = "../data/geojson/" 
dp_prefix_m = "../data/matrix/" 

dp_a_sch = paste(dp_prefix_a, "jc.csv", sep="")
dp_a_hdb = paste(dp_prefix_a, "hdb-property-information.csv", sep="")
dp_a_zip = paste(dp_prefix_a, "sg_zipcode_mapper.csv", sep="")

# Data variables
jc_data <- read.csv(dp_a_sch)
hdb_data <- read.csv(dp_a_hdb)
zip_data <- read.csv(dp_a_zip)

sf_mpsz = st_read(dsn = dp_prefix_g, layer = "MP14_SUBZONE_WEB_PL")

mpsz <- as(sf_mpsz, "Spatial")

jc_data$POSTAL <- as.numeric(jc_data$POSTAL)
jc<- jc_data%>% 
  dplyr::select("SCHOOL"='SEARCHVAL', 'POSTAL', 'LATITUDE', 'LONGITUDE', 'X', 'Y', 'ROAD_NAME')


hdb <- zip_data%>%
  dplyr::select('ADDRESS' = 'address', 'POSTAL'="postal", 'LATITUDE' = 'latitude', 'LONGITUDE' = 'longtitude', 'ROAD_NAME' = 'road_name')



crsobj = CRS("+init=EPSG:3414")
coordinates(jc)<-~LONGITUDE+LATITUDE
proj4string(jc) = crsobj

coordinates(hdb)<-~LONGITUDE+LATITUDE
proj4string(hdb) = crsobj
```



```{r}
library(httr)
get_geojson<-function(lat,lng,filename){

current <- GET(
  "http://localhost:8080/otp/routers/current/isochrone",
  query = list(
    fromPlace = paste(lat,lng,sep = ","), # latlong of place
    mode = "WALK,TRANSIT", # modes we want the route planner to use
    date = "05-11-2020",
    time= "07:00am",
    maxWalkDistance = 1600, # in metres
    walkReluctance = 5,
    minTransferTime = 60, # in secs
    cutoffSec = 900,
    cutoffSec = 1800,
    cutoffSec = 2700,
    cutoffSec = 3600
  )
)

current <- content(current, as = "text", encoding = "UTF-8")
write(current, file = paste(dp_prefix_j,filename,".geojson"))
}

```


```{r}
library(tidyverse)
library(leaflet)

iso <- geojsonio::geojson_read("C:/geojson/ Changi-Terminal-1 .geojson",
  what = "sp")

pal=c('cyan','gold','tomato','red')

leaflet(iso) %>%
    setView(lng = 103.8198, lat = 1.3521, zoom = 11) %>%
  addProviderTiles(providers$CartoDB.DarkMatter,
                   options = providerTileOptions(opacity = 0.8))%>%  
  addPolygons(stroke = TRUE, weight=0.5,
              smoothFactor = 0.3, color="black",
              fillOpacity = 0.1,fillColor =pal ) %>%
  addLegend(position="bottomleft",colors=rev(c("lightskyblue","greenyellow","gold","tomato")),
            labels=rev(c("60 min","45 min",
                     "30 min","15 min")),
            opacity = 0.6,
            title="Travel Time with Public Transport")
```


isochrone generation for all JC 
saves the isochrone generation for each JC as .rds in data/geojson/
Only run this code chunk if you want to generate the .rds files 
```{r}
#isochrone generation for all school - WARNING IO intensive, may take to an hour to run
for (i in 1:10){
  lsch = jc@data[i,'SCHOOL']
  print(lsch)
  lat = jc@coords[i,2]
  long = jc@coords[i,1]
  print(lat)
  print(long)

 iso = get_geojson(lat, long, jc@data[i,'SCHOOL'])
 sp = geojsonio::geojson_read(iso, what = "sp")
 proj4string(sp) = proj4string(hdb)
 res = colSums(gContains(sp, hdb, byid = TRUE))
 print(res)
 res = tbl_df(res)
 colnames(res) = 'blocks'
 sp@data = bind_cols(sp@data, res)
 saveRDS(sp, file = paste0(dp_prefix_j, '/', lsch, '.rds'))
}
```

