PAGE_TITLE <- "Junior Colleges near you"
NOTI_ITEM_STYLE <- "display: inline-block; vertical-align: top;"

notifications <- dropdownMenu(type = "notifications", badgeStatus="primary", icon=icon("info-circle"),
                              notificationItem(icon=icon("info-circle"), status="primary",
                                               text = tags$div(tags$b("Filter Region(s):"),
                                                               tags$br(),
                                                               "Select the region that you want",
                                                               tags$br(),
                                                               "to focus on. This helps to narrow",
                                                               tags$br(),
                                                               "down your search for a Junior",
                                                               tags$br(),
                                                               "College.",
                                                               style=NOTI_ITEM_STYLE)),
                              
                              notificationItem(icon=icon("info-circle"), status="primary",
                                               text = tags$div(tags$b("Junior College:"),
                                                               tags$br(),
                                                               "Select the Junior College that",
                                                               tags$br(),
                                                               "you want to analyze on.",
                                                               style=NOTI_ITEM_STYLE)),
                              
                              notificationItem(icon=icon("info-circle"), status="primary",
                                               text = tags$div(tags$b("Analysis types:"),
                                                               tags$br(),
                                                               
                                                               tags$u("Isochrone:"), 
                                                               "measures the",
                                                               tags$br(),
                                                               "accessibility of a Junior College",
                                                               tags$br(),
                                                               "based on how long it will take to",
                                                               tags$br(),
                                                               "travel from a certain point and",
                                                               tags$br(),
                                                               "time to the Junior College. The",
                                                               tags$br(),
                                                               "shorter the duration, the higher",
                                                               tags$br(),
                                                               "the accessibility of the school",
                                                               tags$br(),
                                                               "from the HDB point.",
                                                               tags$br(),
                                                               tags$br(),

                                                               tags$u("Hansen Accessibility (Hansen):"),
                                                               tags$br(),
                                                               "measures the accessibility for each",
                                                               tags$br(),
                                                               "Junior College by looking at the",
                                                               tags$br(),
                                                               "potential that a person is willing",
                                                               tags$br(),
                                                               "to travel to the school based on",
                                                               tags$br(),
                                                               "the distance and duration from",
                                                               tags$br(),
                                                               "the HDB point to the school. The",
                                                               tags$br(),
                                                               "higher the value of Hansen, the",
                                                               tags$br(),
                                                               "higher the accessibility of the",
                                                               tags$br(),
                                                               "school from the HDB point.",
                                                               tags$br(),
                                                               tags$br(),
                                                               
                                                               tags$u("Spatial Accessibility Measure (SAM):"), 
                                                               tags$br(),
                                                               "measures the accessibility for each",
                                                               tags$br(),
                                                               "Junior College by looking at the",
                                                               tags$br(),
                                                               "population of HDB points and",
                                                               tags$br(),
                                                               "supply of a Junior College. The",
                                                               tags$br(),
                                                               "accessibility increase with higher",
                                                               tags$br(),
                                                               "population nearby and supply and",
                                                               tags$br(),
                                                               "decrease with longer distance or",
                                                               tags$br(),
                                                               "time from the HDB point to the",
                                                               tags$br(),
                                                               "school. The higher the value of",
                                                               tags$br(),
                                                               "SAM, the higher the accessibility",
                                                               tags$br(),
                                                               "of the school from the HDB point.",
                                                               style=NOTI_ITEM_STYLE)),
                              
                              notificationItem(icon=icon("info-circle"), status="primary",
                                               text = tags$div(tags$b("Display school points:"),
                                                               tags$br(),
                                                               "Tick this checkbox to show all",
                                                               tags$br(),
                                                               "school points. This allows you",
                                                               tags$br(),
                                                               "to compare the accessibility",
                                                               tags$br(),
                                                               "between schools easily.",
                                                               style=NOTI_ITEM_STYLE)),
                              
                              notificationItem(icon=icon("info-circle"), status="primary",
                                               text = tags$div(tags$b("Accessibility measures:"),
                                                               tags$br(),
                                                               
                                                               tags$u("Hansen:"),
                                                               " ins",
                                                               tags$br(),
                                                               
                                                               tags$u("SAM:"),
                                                               " Spatial Accessibility Measure..",
                                                               
                                                               style=NOTI_ITEM_STYLE))
)


dashboardPage(title=PAGE_TITLE,
    dashboardHeader(title=div(img(src="logo.png", height = 50, align = "left", style="background-color: white;"), 
                              p(PAGE_TITLE, style="font-size:13px; font-family: 'Gill Sans MT';")),
                    notifications),
    
    dashboardSidebar(
        conditionalPanel(
            condition = "input.tabs == 'Interactive Map' || input.tabs == 'Assessibility Measures' || input.tabs == 'JCs Details'",
            selectizeInput("region", "Filter Region(s):", unique(jc@data$REGION),
                        multiple = TRUE, options = list(
                            'plugins' = list('remove_button'),
                            'create' = TRUE,
                            'persist' = FALSE)),
            selectInput("jc", "Junior College:", jc@data$SCHOOL)),
        conditionalPanel(
            condition = "input.tabs == 'Interactive Map'",
            selectInput("analysis", "Analysis:", c("Duration (Isochrone)", 
                                                   "Distance (Hansen)", 
                                                   "Duration (Hansen)", 
                                                   "Distance (SAM)",
                                                   "Duration (SAM)")),
            checkboxGroupInput("schs", "Display school points:", c("Show all school points")),
            checkboxGroupInput("hdbpts", "Display HDB points:", choices=c("Show all HDB points", "Show chosen HDB point")),
            conditionalPanel(
                condition = "input.hdbpts.includes('Show chosen HDB point')",
                searchInput("postal", "Postal Code:", btnSearch = icon("search"))),
            selectInput("maptype", "Map Type:", names(providers)))
    ),
    
    dashboardBody(
        navbarPage("Explore", id="tabs", collapsible=TRUE,
            tabPanel("Interactive Map", tmapOutput("mapPlot"), width = "100%", height = "100%"),
            tabPanel("Assessibility Measures", 
                     fluidRow(
                        box(title="Hansen Boxplot", collapsible = TRUE,
                            plotOutput("hansenPlot")),
                        box(title="SAM Boxplot", collapsible = TRUE,
                            plotOutput("samPlot")))
             ),
            tabPanel("JCs Details", DTOutput("jcTable")),
            tabPanel("HDBs Details", DTOutput("hdbTable")),
            tabPanel(verbatimTextOutput('temp'), title="temp")))
)