languageCode = "en-us"
title = "[insert project title]"
theme = "crab"
baseurl = "https://example.com"

[params]
description = "IS415 Team 9 Project Proposal"
logoimage = "images/logo.png"
# logoimage = "images/blank.jpg"


[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Another item"
url = "/another/"
