languageCode = "en-us"
title = "Merge'R'Us Proposal"
theme = "crab"
baseurl = "https://brave-bhaskara-fc4519.netlify.app/"

[params]
description = "IS415 Project Team 9"
logoimage = "img/logo.png"


[[menu.main]]
weight = 1
name = "Overview"
url = "/"

[[menu.main]]
weight = 2
name = "Reviews"
url = "/a-reviews/"

[[menu.main]]
weight = 3
name = "Approach"
url = "/b-approach/"

[[menu.main]]
weight = 4
name = "Application System"
url = "/c-architecture/"

[[menu.main]]
weight = 5
name = "Application Storyboard"
url = "/d-storyboard/"

[[menu.main]]
weight = 6
name = "Timeline"
url = "/e-timeline/"

[[menu.main]]
weight = 7
name = "References"
url = "/f-references/"

[[menu.main]]
weight = 8
name = "Contact"
url = "/g-contact/"