languageCode = "en-us"
title = "IS415 Team 9"
theme = "crab"
baseurl = "https://brave-bhaskara-fc4519.netlify.app/"

[params]
description = "Project Proposal"
logoimage = "img/logo.png"
# logoimage = "img/blank.jpg"


[[menu.main]]
weight = 1
name = "Overview"
url = "/"

[[menu.main]]
weight = 2
name = "Project Reviews"
url = "/a-reviews/"

[[menu.main]]
weight = 3
name = "Application System"
url = "/c-architecture/"

[[menu.main]]
weight = 4
name = "Timeline"
url = "/e-timeline/"

[[menu.main]]
weight = 5
name = "References"
url = "/f-references/"